module.exports = {
  ERROR_TEXTS: {
    INTERNAL_ERROR: "Internal error, please try again.",
    BAD_REQ: "Bad Request",
  },
  HTTP_STATUS: {
    OK: 200,
    BAD_REQUEST: 400,
    UNPROCESSABLE_REQ: 422,
    INTERNAL_ERROR: 500,
  },
  LOGS: {
    REQ: "Execution started with: ",
    RES: "Execution completed with: ",
    REQ_SUCCESS: "Successfully imported content to the given stack.",
    DOWNLOAD_COMPLETED: "Stack data download complete.",
    DOWNLOAD_FAILED: "Failed to download stack data.",
    DOWNLOAD_START: "Started downloading stack content",
    EXTRACT_STARTED: "Extraction started.",
    EXTARCT_FAILED: "Extraction failed.",
    EXTRACT_COMPLETE: "Extraction complete.",
    SHELL_START: "Started to execute shelljs command: ",
    SHELL_FINISHED: "Finished executing shelljs command: ",
    SHELL_CODE: "Shell exit code: ",
    SHELL_FAILED: "Error occurred while executing a shell command",
    IMPORT_START: "Started to import content.",
    IMPORT_FINISHED: "Finished importing content",
    IMPORT_FAILED: "Something went wrong while importing.",
  },
};
